In [1]:
import pandas as pd
import numpy as np

In [2]:
s1 = pd.Series([2,3,4,5])
s1

0    2
1    3
2    4
3    5
dtype: int64

In [3]:
s1.values

array([2, 3, 4, 5], dtype=int64)

In [4]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
s1.astype

<bound method NDFrame.astype of 0    2
1    3
2    4
3    5
dtype: int64>

In [6]:
s1.describe

<bound method NDFrame.describe of 0    2
1    3
2    4
3    5
dtype: int64>

In [7]:
s1.empty

False

In [8]:
s1

0    2
1    3
2    4
3    5
dtype: int64

In [9]:
s1.get_values

<bound method Series.get_values of 0    2
1    3
2    4
3    5
dtype: int64>

In [10]:
s2 = pd.Series([2,4,6,8,10],index = ['a','b','c','d','e'])

In [11]:
s2

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [12]:
s2['a']

2

In [13]:
s2['b']

4

In [14]:
s2['e']

10

In [15]:
s2[0]

2

In [16]:
s2.loc['a']

2

In [17]:
s2.iloc[0]

2

In [18]:
s2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [19]:
s2.values

array([ 2,  4,  6,  8, 10], dtype=int64)

In [20]:
s2['a'] = 5

In [21]:
s2

a     5
b     4
c     6
d     8
e    10
dtype: int64

In [22]:
s2.head()

a     5
b     4
c     6
d     8
e    10
dtype: int64

In [23]:
s2.head(2)

a    5
b    4
dtype: int64

In [24]:
s2.tail()

a     5
b     4
c     6
d     8
e    10
dtype: int64

In [25]:
s2.tail(3)

c     6
d     8
e    10
dtype: int64

In [26]:
s2.tail(1)

e    10
dtype: int64

In [27]:
s2[s2>5]

c     6
d     8
e    10
dtype: int64

In [28]:
s2[s2<0]

Series([], dtype: int64)

In [29]:
s2[s2<3]

Series([], dtype: int64)

In [30]:
s2.loc['a'] = 2

In [31]:
s2

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [32]:
s2.iloc[0] = 8

In [33]:
s2

a     8
b     4
c     6
d     8
e    10
dtype: int64

In [34]:
np.exp(s2)

a     2980.957987
b       54.598150
c      403.428793
d     2980.957987
e    22026.465795
dtype: float64

In [35]:
np.array(s2)

array([ 8,  4,  6,  8, 10], dtype=int64)

In [36]:
s3 = pd.DataFrame([[2,4,5,6],[2,4,6,7]])

In [37]:
s3

0  1  2  3
0  2  4  5  6
1  2  4  6  7

In [38]:
np.array(s3)

array([[2, 4, 5, 6],
       [2, 4, 6, 7]], dtype=int64)

In [39]:
'b' in s2

True

In [40]:
'a' in s2

True

In [41]:
s4 = pd.Series({'a':np.nan,'b':45,'c':67,'d':23})

In [42]:
s4

a     NaN
b    45.0
c    67.0
d    23.0
dtype: float64

In [43]:
s4.isnull()

a     True
b    False
c    False
d    False
dtype: bool

In [44]:
s4.notnull()

a    False
b     True
c     True
d     True
dtype: bool

In [45]:
s4.name = 'Asad'

In [46]:
s4.index.name = 'pak'

In [47]:
s4

pak
a     NaN
b    45.0
c    67.0
d    23.0
Name: Asad, dtype: float64

# Data Frame

In [48]:
d1 = {'city':['karachi','lahore','rawalpindi','hydrabad'],
      'population':[23000000,1000000,500000,2500000],
     'year':[2010,2010,2010,2012]
     }

In [49]:
d1 = pd.DataFrame(d1)

In [50]:
d1

city  population  year
0     karachi    23000000  2010
1      lahore     1000000  2010
2  rawalpindi      500000  2010
3    hydrabad     2500000  2012

In [51]:
pd.DataFrame(d1,columns=['population','city','year'])

population        city  year
0    23000000     karachi  2010
1     1000000      lahore  2010
2      500000  rawalpindi  2010
3     2500000    hydrabad  2012

In [52]:
pd.DataFrame(d1,columns=['population','city','year','month'])

population        city  year  month
0    23000000     karachi  2010    NaN
1     1000000      lahore  2010    NaN
2      500000  rawalpindi  2010    NaN
3     2500000    hydrabad  2012    NaN

In [53]:
d1.columns

Index(['city', 'population', 'year'], dtype='object')

In [54]:
d1['city']

0       karachi
1        lahore
2    rawalpindi
3      hydrabad
Name: city, dtype: object

In [55]:
d1['population']

0    23000000
1     1000000
2      500000
3     2500000
Name: population, dtype: int64

In [56]:
d1.year

0    2010
1    2010
2    2010
3    2012
Name: year, dtype: int64

In [57]:
d1.population

0    23000000
1     1000000
2      500000
3     2500000
Name: population, dtype: int64

In [58]:
frame2 = pd.DataFrame(d1, columns=['year', 'state', 'pop', 'debt'],
 index=['one', 'two', 'three', 'four',
'five', 'six'])

In [59]:
frame2

year  state  pop  debt
one     NaN    NaN  NaN   NaN
two     NaN    NaN  NaN   NaN
three   NaN    NaN  NaN   NaN
four    NaN    NaN  NaN   NaN
five    NaN    NaN  NaN   NaN
six     NaN    NaN  NaN   NaN

In [60]:
frame2.year = [2010,2000,2018,2020,2019,2017]

In [61]:
frame2

year  state  pop  debt
one    2010    NaN  NaN   NaN
two    2000    NaN  NaN   NaN
three  2018    NaN  NaN   NaN
four   2020    NaN  NaN   NaN
five   2019    NaN  NaN   NaN
six    2017    NaN  NaN   NaN

In [62]:
frame2.loc['three']

year     2018.0
state       NaN
pop         NaN
debt        NaN
Name: three, dtype: float64

In [63]:
frame2['debt'] = np.arange(6.)

In [64]:
frame2

year  state  pop  debt
one    2010    NaN  NaN   0.0
two    2000    NaN  NaN   1.0
three  2018    NaN  NaN   2.0
four   2020    NaN  NaN   3.0
five   2019    NaN  NaN   4.0
six    2017    NaN  NaN   5.0

In [65]:
l1 = pd.Series([2,3,5,6.],index = ['two','three','six','five'])

In [66]:
frame2['debt'] = l1

In [67]:
frame2

year  state  pop  debt
one    2010    NaN  NaN   NaN
two    2000    NaN  NaN   2.0
three  2018    NaN  NaN   3.0
four   2020    NaN  NaN   NaN
five   2019    NaN  NaN   6.0
six    2017    NaN  NaN   5.0

In [68]:
frame2['state'] = ['ohio','ohio','nevada','ohio','nevada','nevada']

In [69]:
frame2

year   state  pop  debt
one    2010    ohio  NaN   NaN
two    2000    ohio  NaN   2.0
three  2018  nevada  NaN   3.0
four   2020    ohio  NaN   NaN
five   2019  nevada  NaN   6.0
six    2017  nevada  NaN   5.0

In [70]:
frame2['asad'] = frame2['state'] == 'ohio'

In [71]:
frame2

year   state  pop  debt   asad
one    2010    ohio  NaN   NaN   True
two    2000    ohio  NaN   2.0   True
three  2018  nevada  NaN   3.0  False
four   2020    ohio  NaN   NaN   True
five   2019  nevada  NaN   6.0  False
six    2017  nevada  NaN   5.0  False

In [72]:
 pop = {'Nevada': {2001: 2.4, 2002: 2.9},
 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}


In [73]:
frame1 = pd.DataFrame(pop)

In [74]:
frame1

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [75]:
frame1.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [76]:
frame3 = pd.DataFrame(frame1, index=[2001, 2002, 2003])
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [77]:
 pdata = {'Ohio': frame3['Ohio'][1:2],
           'Nevada': frame3['Nevada'][1:3]}


In [78]:
pd.DataFrame(pdata)

Ohio  Nevada
2002   3.6     2.9
2003   NaN     NaN

In [79]:
f1 = pd.Series(range(3),index = ['a','b','c'])

In [80]:
f1

a    0
b    1
c    2
dtype: int64

In [81]:
index = f1.index

In [82]:
index

Index(['a', 'b', 'c'], dtype='object')

In [83]:
index[1:]

Index(['b', 'c'], dtype='object')

In [84]:
index[:-1]

Index(['a', 'b'], dtype='object')

In [85]:
label = pd.Index(np.arange(3),dtype = 'int8')

In [86]:
label

Int64Index([0, 1, 2], dtype='int64')

In [87]:
obj = pd.Series([3,-5,4],label)

In [88]:
obj.index

Int64Index([0, 1, 2], dtype='int64')

In [89]:
obj.index is label

True

In [90]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [91]:
frame3.columns.name = 'state'

In [92]:
frame3.index.name = 'year'

In [93]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2003      NaN   NaN

# 5.2 Essential Functionality


## REINDEXING

In [94]:
obj = pd.Series([3,5,-4,6],index = ['d','b','c','a'])
obj

d    3
b    5
c   -4
a    6
dtype: int64

In [95]:
obj2 = obj.reindex(['a','b','c','d'])

In [96]:
obj2

a    6
b    5
c   -4
d    3
dtype: int64

In [97]:
obj3 = pd.Series(['red','purple','yellow'],index = [0,3,6])

In [98]:
obj3

0       red
3    purple
6    yellow
dtype: object

In [99]:
obj4 = obj3.reindex(range(8), method = 'ffill')

In [100]:
obj4

0       red
1       red
2       red
3    purple
4    purple
5    purple
6    yellow
7    yellow
dtype: object

In [101]:
df = pd.DataFrame(np.arange(9).reshape(3,3),index = [0,3,5],columns = ['a','c','d'])

In [102]:
df

a  c  d
0  0  1  2
3  3  4  5
5  6  7  8

In [103]:
df = df.reindex([0,1,2,3,4])

In [104]:
df

a    c    d
0  0.0  1.0  2.0
1  NaN  NaN  NaN
2  NaN  NaN  NaN
3  3.0  4.0  5.0
4  NaN  NaN  NaN

In [105]:
states = ['a','b','c','d']


In [106]:
df.reindex(columns=states)

a   b    c    d
0  0.0 NaN  1.0  2.0
1  NaN NaN  NaN  NaN
2  NaN NaN  NaN  NaN
3  3.0 NaN  4.0  5.0
4  NaN NaN  NaN  NaN

In [107]:
obj = pd.DataFrame(np.arange(9).reshape(3,3), columns = ['a','c','d'], index = [0,2,3])

In [108]:
obj

a  c  d
0  0  1  2
2  3  4  5
3  6  7  8

In [109]:
frame = pd.DataFrame(np.arange(16).reshape(4,4), columns = ['one','two','three','four'], index = ['a','b','c','d'])

In [110]:
frame

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [111]:
frame.drop(['a','d'])

one  two  three  four
b    4    5      6     7
c    8    9     10    11

In [112]:
frame.drop('two',axis=1)

one  three  four
a    0      2     3
b    4      6     7
c    8     10    11
d   12     14    15

In [113]:
frame.drop('four',axis='columns')

one  two  three
a    0    1      2
b    4    5      6
c    8    9     10
d   12   13     14

In [114]:
frame.drop('a',inplace=True)

In [115]:
frame

one  two  three  four
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [116]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
 .....: index=['Ohio', 'Colorado', 'Utah', 'New York'],
 .....: columns=['one', 'two', 'three', 'four'])

In [117]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32

In [119]:
data[0:3]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [120]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [121]:
data[data['three']>6]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data <5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [123]:
data[data<5] = 0

In [124]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
data.loc['Utah',['two','four']]

two      9
four    11
Name: Utah, dtype: int32

In [126]:
data.iloc[2,[1,3]]

two      9
four    11
Name: Utah, dtype: int32

# 5.3 Summarizing and Computing Descriptive Statistics


In [138]:
df = pd.DataFrame([[np.nan,1],[np.nan,np.nan],[2,5],[4,8]],index = ['a','b','c','d'], columns= ['one','two'])

In [139]:
df

one  two
a  NaN  1.0
b  NaN  NaN
c  2.0  5.0
d  4.0  8.0

In [140]:
df.sum()

one     6.0
two    14.0
dtype: float64

In [144]:
df.sum(axis = 'columns')

a     1.0
b     0.0
c     7.0
d    12.0
dtype: float64

In [147]:
df.mean(skipna = True)

one    3.000000
two    4.666667
dtype: float64

In [148]:
df.idxmax()

one    d
two    d
dtype: object

In [149]:
df.cumsum()

one   two
a  NaN   1.0
b  NaN   NaN
c  2.0   6.0
d  6.0  14.0

In [151]:
df.describe()

one       two
count  2.000000  3.000000
mean   3.000000  4.666667
std    1.414214  3.511885
min    2.000000  1.000000
25%    2.500000  3.000000
50%    3.000000  5.000000
75%    3.500000  6.500000
max    4.000000  8.000000

In [154]:
obj = pd.Series(['a','b','b','d']* 4 )

In [155]:
obj.describe()

count     16
unique     3
top        b
freq       8
dtype: object

In [158]:
df.var()

one     2.000000
two    12.333333
dtype: float64

In [160]:
df.std()

one    1.414214
two    3.511885
dtype: float64

In [161]:
import panda_datareader.data as web

ModuleNotFoundError: No module named 'panda_datareader'